=== vishaldhaduk/sip_test/out/production/sip/conf/peers.xsd
<?xml version="1.0"?>
<!--
    This file is part of Peers.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
    
    Copyright 2007, 2008, 2009, 2010 Yohann Martineau 
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://peers.sourceforge.net"
           xmlns="http://peers.sourceforge.net"
           elementFormDefault="qualified">



  <!-- Simple Types -->


  <xs:simpleType name="portType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="65535"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="familyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="audio"/>
      <xs:enumeration value="video"/>
      <xs:enumeration value="other"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="mediaModeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none"/>
      <xs:enumeration value="captureAndPlayback"/>
      <xs:enumeration value="echo"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Complex Types -->


  <xs:complexType name="interfaceType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="address" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="interfaceRefType">
    <xs:attribute name="ref" type="xs:IDREF"/>
  </xs:complexType>

  <xs:complexType name="interfacesType">
    <xs:sequence>
      <xs:element name="interface" type="interfaceType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="networkType">
    <xs:sequence>
      <xs:element name="interfaces" type="interfacesType"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="audioType">
  </xs:complexType>

  <xs:complexType name="videoType">
  </xs:complexType>

  <xs:complexType name="devicesType">
    <xs:sequence>
      <xs:element name="audio" type="audioType"/>
      <xs:element name="video" type="videoType"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="profileType">
    <xs:sequence>
      <xs:element name="userpart" type="xs:string"/>
      <xs:element name="domain" type="xs:string"/>
      <xs:element name="password" type="xs:string"/>
      <xs:element name="outboundProxy" type="xs:string"/>
      <xs:element name="interface" type="interfaceRefType"/>
      <xs:element name="port" type="portType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sipType">
    <xs:sequence>
      <!-- maxOccurs="unbounded" -->
      <xs:element name="profile" type="profileType"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="attributeType">
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="attributesType">
    <xs:sequence>
      <xs:element name="attribute" type="attributeType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="codecType">
    <xs:sequence>
      <xs:element name="family" type="familyType"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="payloadType" type="xs:integer"/>
      <xs:element name="attributes" type="attributesType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="codecsType">
    <xs:sequence>
      <xs:element name="codec" type="codecType" maxOccurs="unbounded"/>
      <xs:element name="mediaMode" type="mediaModeType"
          default="captureAndPlayback"/>
      <xs:element name="mediaDebug" type="xs:boolean" default="false"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="rtpType">
    <xs:sequence>
      <xs:element name="interface" type="interfaceRefType"/>
      <xs:element name="port" type="portType"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="peersType">
    <xs:sequence>
      <xs:element name="network" type="networkType"/>
      <xs:element name="devices" type="devicesType"/>
      <xs:element name="sip" type="sipType"/>
      <xs:element name="codecs" type="codecsType"/>
      <xs:element name="rtp" type="rtpType"/>
    </xs:sequence>
  </xs:complexType>



  <!-- Root Element -->

  <xs:element name="peers" type="peersType"/>

</xs:schema>

=== vishaldhaduk/sip_test/conf/peers.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!--
    This file is part of Peers.
	Local changes
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
    
    Copyright 2007, 2008, 2009, 2010 Yohann Martineau
--><peers xmlns="http://peers.sourceforge.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://peers.sourceforge.net peers.xsd">
  <network>
    <interfaces>
      <!-- interface id is not employed for the moment -->
      <interface id="eth1">
        <name>Ethernet network interface</name>
        <!-- a specific address can be specified here, may you have several
             network interfaces, or several addresses on a specific interface,
             you can specify an address to bind on here. -->
        <!-- Example: 192.168.1.20 -->
        <address/>
      </interface>
    </interfaces>
  </network>
  <devices>
    <audio/>
    <video/>
  </devices>
  <sip>
    <profile>
      <!-- username (corresponding to the user part of your sip uri) -->
      <!-- Example: alice -->
      <userpart>15990</userpart>
      <!-- domain (corresponding to the domain part of your sip uri) -->
      <!-- Example: atlanta.com -->
      <domain>ekiga.net</domain>
      <!-- if password is empty, no REGISTER message is sent -->
      <!-- Example: 1234 -->
      <password>appu1590</password>
      <!-- you can specify an outbound proxy for registration and calls -->
      <!-- Example: sip:192.168.1.20;lr -->
      <outboundProxy/>
      <interface ref="eth1"/>
      <!-- you can specify the sip listening port you want, default value is
           5060 -->
      <!-- Example: 5060 -->
      <port>6060</port>
    </profile>
  </sip>
  <codecs>
    <codec>
      <!-- not used for the moment -->
      <family>audio</family>
      <!-- not used for the moment -->
      <name>PCMU</name>
      <!-- not used for the moment -->
      <payloadType>0</payloadType>
      <!-- not used for the moment -->
      <!--
      <attributes>
        <attribute name="ptime" value="20"/>
      </attributes>
      -->
    </codec>
    <!-- mediaMode corresponds to the way media is managed. Three values are
         possible for this parameter:
           - captureAndPlayback: capture sound from microphone, send
             corresponding rtp packets, receive rtp packets and play those
             packets on speakers.
           - echo: receive rtp packets, do not play them on speakers and send
             those packets to remote party
           - none: no media is capture, played, send nor received -->
    <mediaMode>captureAndPlayback</mediaMode>
    <!-- mediaDebug is a boolean parameter. If set to true, files will be
         created in a media directory in peers.home directory. Those files will
         contain raw data at input and output of microphone, encoder, rtp
         sender, rtp receiver, and speaker. -->
    <mediaDebug>false</mediaDebug>
  </codecs>
  <rtp>
    <interface ref="eth1"/>
    <!-- you can specify the rtp port to use for incoming and outgoing rtp
         traffic -->
    <port>8000</port>
  </rtp>
</peers>
